### PR TITLE
Fix radial and linear gauge values/ticks

### PR DESCRIPTION
**Pull request by vhakulinen**
[Before](http://i.imgur.com/V6yLvrg.png)

[After](http://i.imgur.com/1hvHrmd.png)

### CODE REVIEW

**Comment by vhakulinen** [comment]
[Here](http://imgur.com/bqTCDTW) is correct after picture. I somehow missed the bug before the latest change and uploaded wrong picture in the first post.

**Comment by vhakulinen** [comment]
Also, there are same problems with the linear gauge. It assumes that the ticks goes with even values, while they usually wont.

**Comment by vhakulinen** [comment]
r

**Comment by vhakulinen** [comment]
Fixed the linear gauges with latest commit.

**Comment by Mikhus** [comment]
@vhakulinen, first of all, thank you for contribution! Just to let me understand what the problem is fixed here could you, please, describe the steps (configs) which cause the bug?

**Comment by Mikhus** [comment]
What I can see now that these changes breaks almost everything (try to build and check all the examples), and I do not really understand what the problem you trying to solve here...

**Comment by Mikhus** [comment]
Please, see this [comment](https://github.com/Mikhus/canvas-gauges/issues/84#issuecomment-269078879)

**Comment by vhakulinen** [comment]
@Mikhus I'll get back to this next week when I get back to work.

**Comment by Mikhus** [comment]
Hi, @vhakulinen 
So finally I did implementation for exact-value tick bars, grabbing some piece of code from your implementation represented in this PR, but what we have just here is not enough to cover this functionality correctly. So I have to close it. Please, refer to branch v2.1.1 for changes and implementation. And very big thanks for your contribution!

**Comment by Mikhus** [comment]
Final implementation example is [here](https://rawgit.com/Mikhus/canvas-gauges/master/examples/exact-ticks-bar.html)

**Comment by vhakulinen** [comment]
| but what we have just here is not enough to cover this functionality correctly

This is totally understandable. Also, sweet to have this feature in! I'll be giving it a shot in coming weeks.

**Pull request closed without merging**
